---
- name: check param VAR_Apache_extracting_rolename subElement
  stat:
    path: "{{ VAR_Apache_gathering_dest }}/{{ inventory_hostname }}/Apache24_gathering_windows"
  delegate_to: localhost
  become: no
  register: file_exist

- name: parameter_generate run
  block:
    # 1-01　Apache Install Roleのパラメータ生成
    - name: Execute the parameter_generate module for Apache24_WIN_install
      parameter_generate:
        rolename: "{{ outer_item }}"
        collect_root: "{{ VAR_Apache_gathering_dest }}/{{ inventory_hostname }}/Apache24_gathering_windows"
        dest: "{{ VAR_Apache_extracting_dest }}"
        specific: "python {{ role_path }}/files/Apache24_WIN_install.py"
      when: outer_item == "Apache24_WIN_install"
    # 1-02　Apache設定Roleのパラメータ生成
    - name: Execute the parameter_generate module for Apache24_WIN_setup
      parameter_generate:
        rolename: "{{ outer_item }}"
        collect_root: "{{ VAR_Apache_gathering_dest }}/{{ inventory_hostname }}/Apache24_gathering_windows"
        dest: "{{ VAR_Apache_extracting_dest }}"
        specific: "python {{ role_path }}/files/Apache24_WIN_setup.py"
      when: outer_item == "Apache24_WIN_setup"
    # 1-03　Apache OSセット Roleのパラメータ生成
    - name: Execute the parameter_generate module for Apache24_WIN_ossetup
      parameter_generate:
        rolename: "{{ outer_item }}"
        collect_root: "{{ VAR_Apache_gathering_dest }}/{{ inventory_hostname }}/Apache24_gathering_windows"
        dest: "{{ VAR_Apache_extracting_dest }}"
        specific: "python {{ role_path }}/files/Apache24_WIN_ossetup.py"
      when: outer_item == "Apache24_WIN_ossetup"

  when: file_exist.stat.exists != false